#pragma once
#include "CoreMinimal.h"
#include "Engine/DataAsset.h"
#include "MemoriaNarrativeData.generated.h"
// Generated by Unreal/Tools/generate_narrative_types.py. Optional bits preserve absent vs empty/false.
USTRUCT()
struct MEMORIA_API FMemoriaNarrativeText
{
    GENERATED_BODY()
    UPROPERTY() bool bHasSpeaker = false;
    UPROPERTY() FString Speaker = TEXT("");
    UPROPERTY() bool bHasText = false;
    UPROPERTY() FString Text = TEXT("");
    UPROPERTY() bool bHasTextKo = false;
    UPROPERTY() FString TextKo = TEXT("");
    UPROPERTY() bool bHasNarrate = false;
    UPROPERTY() FString Narrate = TEXT("");
    UPROPERTY() bool bHasNarrateKo = false;
    UPROPERTY() FString NarrateKo = TEXT("");
    UPROPERTY() bool bHasRequiresMemory = false;
    UPROPERTY() FString RequiresMemory = TEXT("");
    UPROPERTY() bool bHasBurnedText = false;
    UPROPERTY() FString BurnedText = TEXT("");
    UPROPERTY() bool bHasBurnedTextKo = false;
    UPROPERTY() FString BurnedTextKo = TEXT("");
};
USTRUCT()
struct MEMORIA_API FMemoriaNarrativePresentation
{
    GENERATED_BODY()
    UPROPERTY() bool bHasCg = false;
    UPROPERTY() FString Cg = TEXT("");
    UPROPERTY() bool bHasPortrait = false;
    UPROPERTY() FString Portrait = TEXT("");
    UPROPERTY() bool bHasSide = false;
    UPROPERTY() FString Side = TEXT("");
    UPROPERTY() bool bHasFadeMs = false;
    UPROPERTY() int32 FadeMs = 0;
    UPROPERTY() bool bHasBurnedPortrait = false;
    UPROPERTY() FString BurnedPortrait = TEXT("");
};
USTRUCT()
struct MEMORIA_API FMemoriaNarrativeGate
{
    GENERATED_BODY()
    UPROPERTY() bool bHasRequiresFlag = false;
    UPROPERTY() FString RequiresFlag = TEXT("");
    UPROPERTY() bool bHasRequiresNotFlag = false;
    UPROPERTY() FString RequiresNotFlag = TEXT("");
    UPROPERTY() bool bHasRequiresMemoryIntact = false;
    UPROPERTY() FString RequiresMemoryIntact = TEXT("");
    UPROPERTY() bool bHasRequiresMemoryGone = false;
    UPROPERTY() FString RequiresMemoryGone = TEXT("");
};
USTRUCT()
struct MEMORIA_API FMemoriaNarrativeEffects
{
    GENERATED_BODY()
    UPROPERTY() bool bHasSetFlag = false;
    UPROPERTY() FString SetFlag = TEXT("");
    UPROPERTY() bool bHasRecordEnding = false;
    UPROPERTY() FString RecordEnding = TEXT("");
    UPROPERTY() bool bHasBurnMemory = false;
    UPROPERTY() FString BurnMemory = TEXT("");
    UPROPERTY() bool bHasCostMemory = false;
    UPROPERTY() FString CostMemory = TEXT("");
    UPROPERTY() bool bHasAllowFadedBurn = false;
    UPROPERTY() bool AllowFadedBurn = false;
    UPROPERTY() bool bHasAddGrains = false;
    UPROPERTY() int32 AddGrains = 0;
    UPROPERTY() bool bHasAddItem = false;
    UPROPERTY() FString AddItem = TEXT("");
    UPROPERTY() bool bHasAddItemCount = false;
    UPROPERTY() int32 AddItemCount = 0;
    UPROPERTY() bool bHasHealPlayer = false;
    UPROPERTY() int32 HealPlayer = 0;
};
USTRUCT()
struct MEMORIA_API FMemoriaNarrativeAction
{
    GENERATED_BODY()
    UPROPERTY() bool bHasAction = false;
    UPROPERTY() FString Action = TEXT("");
    UPROPERTY() bool bHasPath = false;
    UPROPERTY() FString Path = TEXT("");
    UPROPERTY() bool bHasId = false;
    UPROPERTY() FString Id = TEXT("");
    UPROPERTY() bool bHasStartIndex = false;
    UPROPERTY() int32 StartIndex = 0;
    UPROPERTY() bool bHasResumeScene = false;
    UPROPERTY() FString ResumeScene = TEXT("");
    UPROPERTY() bool bHasResumeIndex = false;
    UPROPERTY() int32 ResumeIndex = 0;
};
USTRUCT()
struct MEMORIA_API FMemoriaNarrativeMetadata
{
    GENERATED_BODY()
    UPROPERTY() bool bHasTitle = false;
    UPROPERTY() FString Title = TEXT("");
    UPROPERTY() bool bHasTitleKo = false;
    UPROPERTY() FString TitleKo = TEXT("");
    UPROPERTY() bool bHasChapter = false;
    UPROPERTY() int32 Chapter = 0;
    UPROPERTY() bool bHasBgm = false;
    UPROPERTY() FString Bgm = TEXT("");
};
USTRUCT()
struct MEMORIA_API FMemoriaNarrativeProvenance
{
    GENERATED_BODY()
    UPROPERTY() FString SourceFile;
    UPROPERTY() FString SourceHash;
    UPROPERTY() FString SourceRevision;
    UPROPERTY() FString Dialect;
    UPROPERTY() int32 GroupPosition = 0;
    UPROPERTY() int32 OriginalIndex = 0;
    UPROPERTY() int32 OriginalChoiceIndex = -1;
};
USTRUCT()
struct MEMORIA_API FMemoriaNarrativeSourceHash
{
    GENERATED_BODY()
    UPROPERTY() FString Path;
    UPROPERTY() FString Sha256Utf8Lf;
};
USTRUCT()
struct MEMORIA_API FMemoriaNarrativeImportMetadata
{
    GENERATED_BODY()
    UPROPERTY() int32 SchemaVersion = 1;
    UPROPERTY() FString ContentKind;
    UPROPERTY() FString Dialect;
    UPROPERTY() FString ExtractorVersion;
    UPROPERTY() FString SourceRevision;
    UPROPERTY() TArray<FMemoriaNarrativeSourceHash> Sources;
    UPROPERTY() FString SemanticSha256;
    UPROPERTY() FString IrSha256;
};
USTRUCT()
struct MEMORIA_API FMemoriaFieldChoice
{
    GENERATED_BODY()
    UPROPERTY() FString Id;
    UPROPERTY() int32 OriginalIndex = 0;
    UPROPERTY() FMemoriaNarrativeProvenance Provenance;
    UPROPERTY() FString EffectPhase;
    UPROPERTY() FMemoriaNarrativeText Text;
    UPROPERTY() FMemoriaNarrativePresentation Presentation;
    UPROPERTY() FMemoriaNarrativeGate Gate;
    UPROPERTY() FMemoriaNarrativeEffects Effects;
    UPROPERTY() FMemoriaNarrativeAction Action;
    UPROPERTY() bool bHasJump = false;
    UPROPERTY() int32 Jump = 0;
    FString TextId(const FString& Field) const { return Id + TEXT("/") + Field; }
};
USTRUCT()
struct MEMORIA_API FMemoriaFieldRow
{
    GENERATED_BODY()
    UPROPERTY() FString Id;
    UPROPERTY() int32 OriginalIndex = 0;
    UPROPERTY() FMemoriaNarrativeProvenance Provenance;
    UPROPERTY() FString EffectPhase;
    UPROPERTY() FMemoriaNarrativeText Text;
    UPROPERTY() FMemoriaNarrativePresentation Presentation;
    UPROPERTY() FMemoriaNarrativeGate Gate;
    UPROPERTY() FMemoriaNarrativeEffects Effects;
    UPROPERTY() FMemoriaNarrativeAction Action;
    UPROPERTY() bool bHasJump = false;
    UPROPERTY() int32 Jump = 0;
    FString TextId(const FString& Field) const { return Id + TEXT("/") + Field; }
    UPROPERTY() int32 StorageIndex = 0;
    UPROPERTY() bool bChoicesPresent = false;
    UPROPERTY() TArray<FMemoriaFieldChoice> Choices;
};
USTRUCT()
struct MEMORIA_API FMemoriaFieldDefinition
{
    GENERATED_BODY()
    UPROPERTY() FString Id;
    UPROPERTY() int32 IndexMappingVersion = 1;
    UPROPERTY() FMemoriaNarrativeMetadata Metadata;
    UPROPERTY() TArray<FMemoriaFieldRow> Rows;
};
UCLASS(BlueprintType)
class MEMORIA_API UMemoriaFieldAsset : public UPrimaryDataAsset
{
    GENERATED_BODY()
public:
    UPROPERTY() FMemoriaNarrativeImportMetadata ImportMetadata;
    UPROPERTY() FMemoriaFieldDefinition Definition;
};
USTRUCT()
struct MEMORIA_API FMemoriaVNChoice
{
    GENERATED_BODY()
    UPROPERTY() FString Id;
    UPROPERTY() int32 OriginalIndex = 0;
    UPROPERTY() FMemoriaNarrativeProvenance Provenance;
    UPROPERTY() FString EffectPhase;
    UPROPERTY() FMemoriaNarrativeText Text;
    UPROPERTY() FMemoriaNarrativePresentation Presentation;
    UPROPERTY() FMemoriaNarrativeGate Gate;
    UPROPERTY() FMemoriaNarrativeEffects Effects;
    UPROPERTY() FMemoriaNarrativeAction Action;
    UPROPERTY() bool bHasJump = false;
    UPROPERTY() int32 Jump = 0;
    FString TextId(const FString& Field) const { return Id + TEXT("/") + Field; }
};
USTRUCT()
struct MEMORIA_API FMemoriaVNStep
{
    GENERATED_BODY()
    UPROPERTY() FString Id;
    UPROPERTY() int32 OriginalIndex = 0;
    UPROPERTY() FMemoriaNarrativeProvenance Provenance;
    UPROPERTY() FString EffectPhase;
    UPROPERTY() FMemoriaNarrativeText Text;
    UPROPERTY() FMemoriaNarrativePresentation Presentation;
    UPROPERTY() FMemoriaNarrativeGate Gate;
    UPROPERTY() FMemoriaNarrativeEffects Effects;
    UPROPERTY() FMemoriaNarrativeAction Action;
    UPROPERTY() bool bHasJump = false;
    UPROPERTY() int32 Jump = 0;
    FString TextId(const FString& Field) const { return Id + TEXT("/") + Field; }
    UPROPERTY() int32 StorageIndex = 0;
    UPROPERTY() bool bChoicesPresent = false;
    UPROPERTY() TArray<FMemoriaVNChoice> Choices;
};
USTRUCT()
struct MEMORIA_API FMemoriaVNDefinition
{
    GENERATED_BODY()
    UPROPERTY() FString Id;
    UPROPERTY() int32 IndexMappingVersion = 1;
    UPROPERTY() FMemoriaNarrativeMetadata Metadata;
    UPROPERTY() TArray<FMemoriaVNStep> Steps;
};
UCLASS(BlueprintType)
class MEMORIA_API UMemoriaVNAsset : public UPrimaryDataAsset
{
    GENERATED_BODY()
public:
    UPROPERTY() FMemoriaNarrativeImportMetadata ImportMetadata;
    UPROPERTY() FMemoriaVNDefinition Definition;
};
