"""S330: extract the memories a chapter brings from scripts/systems/memory_manager.gd.

add_chapter_memories(chapter) adds the chapter's memories that Arrel does not hold yet. This reads the
`match chapter:` cases of the connected canon (Chapters 3 to 5) and their MEMORY_TEXT_KO rows and writes

  docs/unreal-migration/ir/chapter_memories.v1.json                          (reviewable)
  Unreal/Memoria/Source/Memoria/Private/Domain/MemoriaChapterMemorySources.inl   (compiled in, ASCII)

Usage: python export_chapter_memories.py [--check]
"""
import argparse
import json
import re
from pathlib import Path

from export_journal import literal

ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT / 'scripts/systems/memory_manager.gd'
OUT = ROOT / 'docs/unreal-migration/ir/chapter_memories.v1.json'
INL = ROOT / 'Unreal/Memoria/Source/Memoria/Private/Domain/MemoriaChapterMemorySources.inl'
# The source's connected canon ends after Chapter 5 (docs/SEASON1_GAME_PROGRESSION.md).
CHAPTERS = (3, 4, 5)
# enum MemoryGrade { GRADE_5, GRADE_4, GRADE_3, GRADE_2, GRADE_1 }
GRADES = {'GRADE_5': 0, 'GRADE_4': 1, 'GRADE_3': 2, 'GRADE_2': 3, 'GRADE_1': 4}
MEMORY = re.compile(
    r'Memory\.new\(\s*"([^"]+)",\s*"([^"]*)",\s*"([^"]*)",\s*MemoryGrade\.(GRADE_\d),\s*(\d+)'
    r'(?:,\s*"([^"]*)")?(?:,\s*"([^"]*)")?\s*\)')


def extract():
    src = SOURCE.read_text(encoding='utf-8').replace('\r\n', '\n')
    start = src.index('func add_chapter_memories(chapter: int) -> void:')
    body = src[start:src.index('\nfunc ', start + 1)]
    ko = literal(src, r'const MEMORY_TEXT_KO: Dictionary = \{')
    chapters = {}
    for chapter in CHAPTERS:
        case = re.search(r'\n\t\t%d:\n(.*?)(?=\n\t\t\d+:\n|\Z)' % chapter, body, re.S)
        if not case:
            raise ValueError('Missing chapter case %d' % chapter)
        rows = []
        for m in MEMORY.finditer(case.group(1)):
            mid, title, desc, grade, power, effect, npc = m.groups()
            # Every add is guarded by `if not _has_memory(id)`: the grant is idempotent.
            if 'if not _has_memory("%s")' % mid not in case.group(1):
                raise ValueError('Unguarded chapter memory ' + mid)
            text = ko.get(mid)
            if not text or not text.get('title') or not text.get('desc'):
                raise ValueError('Missing Korean text for ' + mid)
            row = {'id': mid, 'title': title, 'description': desc, 'grade': GRADES[grade], 'burn_power': int(power),
                   'story_effect': effect or '', 'related_npc': npc or '',
                   'ko': {'title': text['title'], 'description': text['desc'], 'story_effect': text.get('effect', '')}}
            if bool(row['story_effect']) != bool(row['ko']['story_effect']):
                raise ValueError('Story effect text mismatch for ' + mid)
            rows.append(row)
        if not rows:
            raise ValueError('No memories for chapter %d' % chapter)
        chapters[str(chapter)] = rows
    return {'schema_version': 1, 'source': 'scripts/systems/memory_manager.gd::add_chapter_memories', 'chapters': chapters}


def inl(value):
    text = json.dumps(value, ensure_ascii=True, sort_keys=True, separators=(',', ':')).replace('\\', '\\\\').replace('"', '\\"')
    chunks, i = [], 0
    while i < len(text):
        j = min(i + 2000, len(text))
        while j < len(text) and text[j - 1] == '\\':
            j += 1
        chunks.append(text[i:j]); i = j
    lines = ['// Generated by Unreal/Tools/export_chapter_memories.py from scripts/systems/memory_manager.gd; do not hand edit.',
             'static const TCHAR* const MemoriaChapterMemorySourceParts[] = {']
    lines += ['    TEXT("%s"),' % c for c in chunks] + ['};']
    return '\n'.join(lines) + '\n'


def main():
    p = argparse.ArgumentParser(); p.add_argument('--check', action='store_true')
    a = p.parse_args()
    value = extract()
    outputs = {OUT: json.dumps(value, ensure_ascii=False, indent=1, sort_keys=True) + '\n', INL: inl(value)}
    if a.check:
        stale = [str(p) for p, t in outputs.items() if not p.exists() or p.read_text(encoding='utf-8') != t]
        print('MEMORIA_CHAPTER_MEMORIES_' + ('STALE ' + ' '.join(stale) if stale else 'PASS'))
        return 1 if stale else 0
    for path, text in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True); path.write_text(text, encoding='utf-8', newline='\n')
    print('MEMORIA_CHAPTER_MEMORIES_WRITTEN ' + ' '.join('ch%s=%d' % (k, len(v)) for k, v in value['chapters'].items()))
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
