"""Generate explicit reflected optional primitives, never authored story values."""
from pathlib import Path
import argparse
from narrative_ir import ROOT, TEXT, PRESENTATION, GATE, EFFECTS, ACTION, INTEGER, BOOLEAN

GROUPS = {'Text':TEXT, 'Presentation':PRESENTATION, 'Gate':GATE, 'Effects':EFFECTS, 'Action':ACTION,
          'Metadata':('title','title_ko','chapter','bgm')}

def name(k): return ''.join(x.capitalize() for x in k.split('_'))

def outputs():
    h=['#pragma once', '#include "CoreMinimal.h"', '#include "Engine/DataAsset.h"',
       '#include "MemoriaNarrativeData.generated.h"',
       '// Generated by Unreal/Tools/generate_narrative_types.py. Optional bits preserve absent vs empty/false.']
    cpp=['// Generated typed primitive codecs; strict key/type checks, no runtime JSON dependency.']
    for group, keys in GROUPS.items():
        h += ['USTRUCT()',f'struct MEMORIA_API FMemoriaNarrative{group}', '{', '    GENERATED_BODY()']
        read=[f'bool Read{group}(const Obj& O, FMemoriaNarrative{group}& D)', '{', '    if (!O) return false;']
        write=[f'Obj Write{group}(const FMemoriaNarrative{group}& D)', '{', '    auto O=MakeShared<FJsonObject>();']
        for k in keys:
            n=name(k); typ='int32' if k in INTEGER or k=='chapter' else ('bool' if k in BOOLEAN else 'FString')
            default='false' if typ=='bool' else ('0' if typ=='int32' else 'TEXT("")')
            h += [f'    UPROPERTY() bool bHas{n} = false;',f'    UPROPERTY() {typ} {n} = {default};']
            read += [f'    D.bHas{n}=Has(O,TEXT("{k}"));', f'    if (D.bHas{n} && !Read{typ}(O,TEXT("{k}"),D.{n})) return false;']
            setter='SetNumberField' if typ=='int32' else ('SetBoolField' if typ=='bool' else 'SetStringField')
            write += [f'    if (D.bHas{n}) O->{setter}(TEXT("{k}"),D.{n});']
        read += ['    return KeysSubset(O, {'+','.join(f'TEXT("{k}")' for k in keys)+'});', '}']
        write += ['    return O;', '}']
        h += ['};']; cpp+=read+write
    h += ['''USTRUCT()
struct MEMORIA_API FMemoriaNarrativeProvenance
{
    GENERATED_BODY()
    UPROPERTY() FString SourceFile;
    UPROPERTY() FString SourceHash;
    UPROPERTY() FString SourceRevision;
    UPROPERTY() FString Dialect;
    UPROPERTY() int32 GroupPosition = 0;
    UPROPERTY() int32 OriginalIndex = 0;
    UPROPERTY() int32 OriginalChoiceIndex = -1;
};
USTRUCT()
struct MEMORIA_API FMemoriaNarrativeSourceHash
{
    GENERATED_BODY()
    UPROPERTY() FString Path;
    UPROPERTY() FString Sha256Utf8Lf;
};
USTRUCT()
struct MEMORIA_API FMemoriaNarrativeImportMetadata
{
    GENERATED_BODY()
    UPROPERTY() int32 SchemaVersion = 1;
    UPROPERTY() FString ContentKind;
    UPROPERTY() FString Dialect;
    UPROPERTY() FString ExtractorVersion;
    UPROPERTY() FString SourceRevision;
    UPROPERTY() TArray<FMemoriaNarrativeSourceHash> Sources;
    UPROPERTY() FString SemanticSha256;
    UPROPERTY() FString IrSha256;
};''']
    # Two explicit choice and row types: no runtime choice index is baked in definitions.
    for d, rowname in [('Field','Row'),('VN','Step')]:
        for choice in (True,False):
            suffix='Choice' if choice else rowname
            h+=['USTRUCT()',f'struct MEMORIA_API FMemoria{d}{suffix}', '{', '    GENERATED_BODY()',
                '    UPROPERTY() FString Id;', '    UPROPERTY() int32 OriginalIndex = 0;',
                '    UPROPERTY() FMemoriaNarrativeProvenance Provenance;', '    UPROPERTY() FString EffectPhase;']
            for group in ('Text','Presentation','Gate','Effects','Action'):
                h += [f'    UPROPERTY() FMemoriaNarrative{group} {group};']
            h += ['    UPROPERTY() bool bHasJump = false;', '    UPROPERTY() int32 Jump = 0;',
                  '    FString TextId(const FString& Field) const { return Id + TEXT("/") + Field; }']
            if not choice:
                h += ['    UPROPERTY() int32 StorageIndex = 0;', '    UPROPERTY() bool bChoicesPresent = false;',
                      f'    UPROPERTY() TArray<FMemoria{d}Choice> Choices;']
            h += ['};']
        h += ['USTRUCT()',f'struct MEMORIA_API FMemoria{d}Definition', '{','    GENERATED_BODY()',
              '    UPROPERTY() FString Id;', '    UPROPERTY() int32 IndexMappingVersion = 1;',
              '    UPROPERTY() FMemoriaNarrativeMetadata Metadata;',
              f'    UPROPERTY() TArray<FMemoria{d}{rowname}> '+('Rows' if d=='Field' else 'Steps')+';', '};',
              'UCLASS(BlueprintType)',f'class MEMORIA_API UMemoria{d}Asset : public UPrimaryDataAsset', '{','    GENERATED_BODY()', 'public:',
              '    UPROPERTY() FMemoriaNarrativeImportMetadata ImportMetadata;',f'    UPROPERTY() FMemoria{d}Definition Definition;', '};']
    return {ROOT/'Unreal/Memoria/Source/Memoria/Public/Narrative/MemoriaNarrativeData.h':'\n'.join(h)+'\n',
            ROOT/'Unreal/Memoria/Source/MemoriaTests/Private/Import/MemoriaNarrativeCodecs.inl':'\n'.join(cpp)+'\n'}

if __name__=='__main__':
    p=argparse.ArgumentParser(); p.add_argument('--check',action='store_true'); a=p.parse_args()
    for path, value in outputs().items():
        if a.check:
            if path.read_text(encoding='utf-8') != value: raise SystemExit('Generated typed definitions differ: '+str(path))
        else: path.write_text(value, encoding='utf-8', newline='\n')
